# Generated by Django 5.1 on 2024-08-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=250)),
                ('taskDescription', models.TextField()),
                ('Task_Assign_Date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
