# Generated by Django 5.0.7 on 2024-08-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCategory', '0001_initial'),
        ('TaskModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='category',
            field=models.ManyToManyField(to='TaskCategory.taskcategory'),
        ),
    ]
